#!/usr/bin/env bash
# Pre-release hook for the release script: https://github.com/welpo/release
VERSION_TAG="$1"
VERSION="${VERSION_TAG#v}"  # Remove the 'v' prefix.

# Update pyproject.toml
poetry version "$VERSION"
