name: Lint pull request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

permissions:
  pull-requests: read

jobs:
  main:
    name: Run git-sumi
    runs-on: ubuntu-24.04
    steps:
      - uses: welpo/git-sumi-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_SUMI_MAX_HEADER_LENGTH: ${{ contains(github.event.pull_request.title, 'deps:') && '80' || '' }} # Allow longer titles for dependency updates.
